// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"mygo/internal/controller"
	"mygo/internal/db"
	"mygo/internal/repository"
	"mygo/internal/service"
)

// Injectors from wire.go:

func InitAppControllers() *AppControllers {
	gormDB := db.GetDB()
	articleRepository := repository.NewArticleRepository(gormDB)
	articleService := service.NewArticleService(articleRepository)
	articleController := controller.NewArticleController(articleService)
	categoryRepository := repository.NewCategoryRepository(gormDB)
	categoryService := service.NewCategoryService(categoryRepository)
	categoryController := controller.NewCategoryController(categoryService)
	tagRepository := repository.NewTagRepository(gormDB)
	tagService := service.NewTagService(tagRepository)
	tagController := controller.NewTagController(tagService)
	userRepository := repository.NewUserRepository(gormDB)
	userService := service.NewUserService(userRepository)
	userController := controller.NewUserController(userService)
	metaDataRepository := repository.NewMetaDataRepository(gormDB)
	metaDataService := service.NewMetaDataService(metaDataRepository)
	metaDataController := controller.NewMetaDataController(metaDataService)
	appControllers := &AppControllers{
		ArticleCtrl:  articleController,
		CategoryCtrl: categoryController,
		TagCtrl:      tagController,
		UserCtrl:     userController,
		MetaDataCtrl: metaDataController,
	}
	return appControllers
}

// wire.go:

var ArticleSet = wire.NewSet(repository.NewArticleRepository, service.NewArticleService, controller.NewArticleController)

var CategorySet = wire.NewSet(repository.NewCategoryRepository, service.NewCategoryService, controller.NewCategoryController)

var TagSet = wire.NewSet(repository.NewTagRepository, service.NewTagService, controller.NewTagController)

var UserSet = wire.NewSet(repository.NewUserRepository, service.NewUserService, controller.NewUserController)

var MetaDataSet = wire.NewSet(repository.NewMetaDataRepository, service.NewMetaDataService, controller.NewMetaDataController)

var ProviderSetAll = wire.NewSet(
	ArticleSet,
	CategorySet,
	TagSet,
	UserSet,
	MetaDataSet,
)

type AppControllers struct {
	ArticleCtrl  *controller.ArticleController
	CategoryCtrl *controller.CategoryController
	TagCtrl      *controller.TagController
	UserCtrl     *controller.UserController
	MetaDataCtrl *controller.MetaDataController
}
